INSERT INTO PERSONS (PERSON_ID, FIRST_NAME, LAST_NAME, ADDRESS, City)
VALUES ('1', 'Tom', 'Cardinal', 'Stavanger', 'Norway');
INSERT INTO PERSONS (PERSON_ID, FIRST_NAME, LAST_NAME, ADDRESS, City)
VALUES ('2', 'Wilman', 'Cardinal', 'Wolla', 'Chennai');


INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, SALARY)
VALUES (1201, 'Electronics', 50000 );
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, SALARY)
VALUES (2, 'Robatics', 70000 );