DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID int,
    DEPARTMENT_NAME varchar(255),
    SALARY int
);

DROP TABLE IF EXISTS PERSONS;
CREATE TABLE PERSONS (
    PERSON_ID int,
    FIRST_NAME varchar(255),
    LAST_NAME varchar(255),
    ADDRESS varchar(255),
    CITY varchar(255)
);
